version: '2'
services:
  app:
    build: .
    container_name: rate_service
    restart: always
    ports:
      - 127.0.0.1:4568:4568
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
